### ISSUE TITLE
Data Download

### ISSUE THREAD

**Issue by samkml** [jonpappalord/crowd_flow_prediction#2]
Hi 
I am trying to download the BikeNYC data name : NYC14_M16x8_T60_NewEnd.h5, 
based on Readme: Download data from [OneDrive](https://1drv.ms/f/s!Akh6N7xv3uVmhOhGxkRDfGTigqAyZw) or [BaiduYun](http://pan.baidu.com/s/1mhIPrRE)
But I could not. No file in onedirve. and the Chinese website ask for sign up with Chinese phone number.
Can anyone help please?

Thanks

**Comment by cardiamc** [comment]
Hi, you can find the file here:
https://drive.google.com/file/d/1ghFXjzWUe0aAVVEEOmiEW9qhwVh-tsun/view?usp=drive_link

**Comment by samkml** [comment]
Hi Marco,

Please provide access to GDrive.

Thanks,
Samira

**Comment by samkml** [comment]
Hi Marco,

Thanks for sharing the data. I got an error in running the code. Though I am not sure if I shall write it here. it will be very helpful if you could give an opinion on that. When I run the main.py , I face the following error :

(crowdflowenv) D:\crowd_flow_prediction>python main.py
Traceback (most recent call last):
  File "D:\crowd_flow_prediction\main.py", line 2, in <module>
    from src.AdjNet.trainModel import train_and_evaluate
  File "D:\crowd_flow_prediction\src\AdjNet\trainModel.py", line 11, in <module>
    from src.AdjNet.utils.config import Config
  File "D:\crowd_flow_prediction\src\AdjNet\utils\config.py", line 29, in <module>
    class Config(metaclass=Config_setup):
TypeError: Config_setup.__init__() takes from 1 to 2 positional arguments but 4 were given

**Comment by samkml** [comment]
Hi Marco,

Thanks for sharing the data. I got an error in running the code. It
would be very helpful if you could give an opinion on that. When I run the
main.py , I face the following error :

(crowdflowenv) D:\crowd_flow_prediction>python main.py
Traceback (most recent call last):
File "D:\crowd_flow_prediction\main.py", line 2, in
from src.AdjNet.trainModel import train_and_evaluate
File "D:\crowd_flow_prediction\src\AdjNet\trainModel.py", line 11, in
from src.AdjNet.utils.config import Config
File "D:\crowd_flow_prediction\src\AdjNet\utils\config.py", line 29, in
class Config(metaclass=Config_setup):
TypeError: Config_setup.*init*() takes from 1 to 2 positional arguments but
4 were given



Thanks,

Samira
